version: '2'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/html:/etc/nginx/html
    networks:
      - app

  main:
    image: jsreportonline/main
    ports:
      - "5488:5488"
    env_file: configuration.env
    restart: always
    volumes:
      - /tmp:/tmp
    networks:
      - app

  workers:
    image: jsreportonline/workers
    ports:
      - "1000:1000"
    env_file: configuration.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app
      - nt1
      - np1
      - nw1
      - nf1
  
  t1:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t1
    volumes:
      - /tmp/jsreport-temp:/tmp
    networks:
      - nt1
  
  p1:
    image: jsreportonline/phantom-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: p1
    volumes:
      - /tmp/jsreport-temp:/tmp
    networks:
      - np1
  
  w1:
    image: jsreportonline/wkhtmltopdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: w1
    volumes:
      - /tmp/jsreport-temp:/tmp
    environment:
      - temp=/tmp
    networks:
      - nw1
  
  f1:
    image: jsreportonline/fop-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 2568m
    container_name: f1
    volumes:
      - /tmp/jsreport-temp:/tmp
    environment:
      - temp=/tmp
    networks:
      - nf1
  
networks:
  app:
    driver: bridge
  nt1:
    driver: bridge
  np1:
    driver: bridge
  nw1:
    driver: bridge
  nf1:
    driver: bridge    
