version: '2'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/html:/etc/nginx/html
    networks:
      - app

  main:
    image: jsreportonline/main
    ports:
      - "5488:5488"
    env_file: configuration.env
    restart: always
    volumes:
      - /tmp:/tmp
    networks:
      - app

  workers:
    image: jsreportonline/workers
    ports:
      - "1000:1000"
    env_file: configuration.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app
      - nt1
      - nt2
      - nt3
      - nt4
      - nt5
      - nt6
      - nt7
      - nt8
      - np1
      - np2
      - np3
      - np4
      - np5
      - nw1
      - nw2
      - nf1
      - nf2
  
  t1:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt1
  
  t2:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt2
  
  t3:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt3
  
  t4:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt4
  
  t5:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt5
  
  t6:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt6
  
  t7:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt7
  
  t8:
    image: jsreportonline/tasks
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: t8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nt8
  
  p1:
    image: jsreportonline/phantom-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: p1
    volumes:
      - /tmp/jsreport-temp:/tmp
    networks:
      - np1
  
  p2:
    image: jsreportonline/phantom-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: p2
    volumes:
      - /tmp/jsreport-temp:/tmp
    networks:
      - np2
  
  p3:
    image: jsreportonline/phantom-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: p3
    volumes:
      - /tmp/jsreport-temp:/tmp
    networks:
      - np3
  
  p4:
    image: jsreportonline/phantom-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: p4
    volumes:
      - /tmp/jsreport-temp:/tmp
    networks:
      - np4
  
  p5:
    image: jsreportonline/phantom-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: p5
    volumes:
      - /tmp/jsreport-temp:/tmp
    networks:
      - np5
  
  w1:
    image: jsreportonline/wkhtmltopdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: w1
    volumes:
      - /tmp/jsreport-temp:/tmp
    environment:
      - temp=/tmp
    networks:
      - nw1
  
  w2:
    image: jsreportonline/wkhtmltopdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 128m
    container_name: w2
    volumes:
      - /tmp/jsreport-temp:/tmp
    environment:
      - temp=/tmp
    networks:
      - nw2
  
  f1:
    image: jsreportonline/fop-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 2568m
    container_name: f1
    volumes:
      - /tmp/jsreport-temp:/tmp
    environment:
      - temp=/tmp
    networks:
      - nf1
  
  f2:
    image: jsreportonline/fop-pdf
    read_only: true
    cpu_quota: 25000
    restart: always
    mem_limit: 2568m
    container_name: f2
    volumes:
      - /tmp/jsreport-temp:/tmp
    environment:
      - temp=/tmp
    networks:
      - nf2
  
networks:
  app:
    driver: bridge
  nt1:
    driver: bridge
  nt2:
    driver: bridge
  nt3:
    driver: bridge
  nt4:
    driver: bridge
  nt5:
    driver: bridge
  nt6:
    driver: bridge
  nt7:
    driver: bridge
  nt8:
    driver: bridge
  np1:
    driver: bridge
  np2:
    driver: bridge
  np3:
    driver: bridge
  np4:
    driver: bridge
  np5:
    driver: bridge
  nw1:
    driver: bridge
  nw2:
    driver: bridge
  nf1:
    driver: bridge
  nf2:
    driver: bridge    